FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libreadline-dev xxd libssl-dev libffi-dev

COPY . /repo
WORKDIR /repo
RUN make -j8

FROM ubuntu:20.04 as package
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libreadline-dev libssl-dev
COPY --from=builder /repo/tpl /
